### ISSUE TITLE
Revisit deprecation of GCS storage backend

### ISSUE THREAD

**Issue by Jonpez2** [buildbarn/bb-storage#147] opened 2022-10-18 16:50 UTC
Given the massive performance improvements in GCS, would it be interesting to revisit its deprecation as a storage backend?

https://cloud.google.com/blog/products/storage-data-transfer/new-gcloud-storage-cli-for-your-data-transfers

Thanks!

**Comment by EdSchouten** [comment] 2022-10-19 13:08
I think 'raw performance' was never the reason for us to deprecate the GCS/S3 storage backend. It was always the inability to do batch existence queries. This is something that needs to be fast for Buildbarn to work efficiently.

Please see #128 for more discussion in this area.

**Comment by Jonpez2** [comment] 2022-10-19 17:12
Thank you, that's a super helpful link, sorry for blindly reopening the conversation.

**Comment by Jonpez2** [comment] 2022-10-19 17:25
So I assume that a parallel call - one per object - over the gcp storage grpc list api was considered and discarded?

**Comment by Jonpez2** [comment] 2022-10-21 07:18
So I've started messing around with the codebase, and the first thing I needed to do was to add a dependency on the Spanner API, after which I ran go mod tidy on the root of the repo.  This errored out with:

go: finding module for package github.com/buildbarn/bb-storage/internal/mock
github.com/buildbarn/bb-storage/pkg/auth tested by
        github.com/buildbarn/bb-storage/pkg/auth.test imports
        github.com/buildbarn/bb-storage/internal/mock: no matching versions for query "latest"

Is that expected or am I doing it wrong?

Thanks!

**Comment by Jonpez2** [comment] 2022-10-21 13:35
Seems to give exactly the same error.  I think the problem is that that directory is quite weird in go space, and only defined in bazel space (right?)

**Comment by moroten** [comment] 2022-10-23 21:30
Yes, the problem is the generated files not available in the repository. Does anyone know a good way to deal with it?

For me, `go get -u ./... && go mod tidy -e` has worked. That avoids the test packages and does not feel ideal.

**Comment by EdSchouten** [comment] 2022-10-26 15:13
I don't think I use `go mod tidy` at all. I generally just:
- Remove go.sum
- Remove all the dependencies in go.mod
- Run `go get -d ./...`
And live with that.

**Comment by EdSchouten** [comment] 2023-02-25 17:24
Closing this, as I'm still not convinced this is feasible. GCS may well be faster, but because it still lacks facilities for doing bulk existence checks, it's still not suitable. If I'm wrong, I'd like to be persuaded otherwise in the form of a PR containing benchmark results.

**Closed by EdSchouten** 2023-02-25 17:24 UTC
