### ISSUE TITLE
KeyLocationMapInMemory size recommendation may be too small

### ISSUE THREAD

**Issue by YngveNPettersen** [buildbarn/bb-storage#103] opened 2020-12-21 20:47 UTC
The past few weeks I have investigated an issue with a Buildbarn/Goma upgrade to status early November, testing with our Chromium-based project.

The issue concerned error reports from the workers about "Failed to obtain" directories, usually directories that AFAIK had only subfolders, no files. 

Initially, the problem seemed to be caused by Goma, since I was not able to reproduce in earlier versions, but it turned out that the error was still reported, but not treated as fatal until later (I have not been able to locate that modification, so far).

Eventually, I started testing changes to the cache size, and significantly increased the size of our keyLocationMapOnBlockDevice configuration from it's current 256K *4 *2 items (2M), which was actually supposed to be able to handle two platforms, with two build profiles (2*2=4). 256K * 16 entries was the lowest cache size the test system for a single branch. 256K*10 items did not work, at least in one to two tries.

My guess is that relatively frequently there will be collisions for files, and while source entries are checked before each command, the intermediate subdirectory-only directories, e.g. "out", can get kicked out (in fact, in one case it seems like the top directory was kicked out).

Chromium is a fairly big project, and the source tree totals more than 650K files, the out dir adds 250K more; of these approximately 180K are C/C++ files, and there are up to 60K ninja work items for Linux (some platforms have 90 K), so an estimate of 256K files in a build isn't that far off.

The KeyLocationMapInMemory.entries documentation, which I assume also works for the keyLocationMapOnBlockDevice.sizeBytes entry (with a factor of 64 bytes for each entry), says :

```
    // Recommended value: between 2 and 10 times the expected number of
    // objects stored.

```

My testing seems to indicate that this factor is too low, at least for a project on the size of Chromium; I haven't tried factors between 10 and 16, but I assume that, maybe, I could reduce it to 14, maybe 12, but don't see any reason to try. I will probably up the factor to 32 to be on the safe side for the production system.

I would suggest that the documentation is updated to indicate that even higher factors, such as 16 and 32  are needed for big projects. the keyLocationMapOnBlockDevice should also reference this, as well as the size of each entry.

I would also suggest that this sizing information, as well as all possible configuration file fields are documented either in the README.md file, or an associated file, with links to their definitions in the proto files.

**Comment by EdSchouten** [comment] 2020-12-21 21:20
> Chromium is a fairly big project, and the source tree totals more than 650K files, the out dir adds 250K more; of these approximately 180K are C/C++ files, and there are up to 60K ninja work items for Linux (some platforms have 90 K), so an estimate of 256K files in a build isn't that far off.

Note that the documentation states "the expected number of *objects* stored"; not the number of *files* stored. Simply counting the number of files fails to account for a lot of things:

- Action & Command messages,
- Directory messages, of which there are likely a lot,
- Output files.

Consider working your way backwards. How large is your storage in total? How large do you think the average object is going to be? A couple of KB? Divide the first by the second. Then multiply it by 64. Then multiply it by a constant between 2 and 10. That should be the size of the key-location map.

> I would also suggest that this sizing information, as well as all possible configuration file fields are documented either in the README.md file, or an associated file, with links to their definitions in the proto files.

Why should we document *all possible configuration file fields* in README.md? Isn't this exactly what the documentation strings in the .proto files are for? Coming up with separate documentation that effectively copy-pastes stuff from the .proto files seems like a complete waste of time to me. That's a computer's job, as a documentation generator could do that. Furthermore, there's nothing wrong with spending some time to learn Protobuf, especially if you want to play around with REv2.

You know what would be worth documenting? How to debug issues like these. How did you root cause this? Where there any Prometheus metrics that you looked at while debugging these issues? Are there any Prometheus queries that would make useful alerts?

**Comment by YngveNPettersen** [comment] 2020-12-21 23:59
As mentioned, there are about 180 K source files, and 60K ninja tasks for this particular configuration, which gives an estimated upper limit on source and output object files of 256 K.  (Also, only ~40K of the 90K C/C++ files are actually used by the build, plus some fraction of the ~90K header files)

Additionally, there are about 70K directories in total.

Actual number of object outputs is ~40K, indicating number of actions and each log output is the same for each, 

Total of all that (180K + 70K + 40K*4) is still only ~400K items, which means that the factor of 10 *barely* fits (and the actual number of such items is probably just 300K, since not all the source files are used).

Keep in mind that even with a factor of 5 (based on 400K) , I encountered problems with (I assume) collisions kicking files out. This suggest that, at least for a big project, the 2-10 factor is too small.

If this is indeed caused by hash collision, then my suggestion is that a different organization of the table should be considered. Items should only be kicked out when they have not been used for a long time, not because another item wants to use its parking spot (and remember that this problem occurred in the first build in the cache). Options include multiple entries in a single location, a reference to a different location storing the collisions, or recalculate the location using a different formula, such as using an incrementing value N for each iteration, and using a hash(N|ref) for a ref to calculate a different location. 

The original cache size for the test system, specified in blocksOnBlockDevice, was 80 GB, but that was increased to 200 when I started testing the test parameters; the production system will have a estimated size of 1600-1800 GB total, for all the cache; a separate system under consideration will likely have a cache 3 times that size.

Looking at average file sizes for my project, the source files are about 16 KB each, the object files ~60 KB, which means that the cache would store 60K source files per GB, and 16K object files per GB.

Actual usage in the test runs I have been running is ~8GB in the CAS storage directories (much less than either 80 or 200 that I specified), which lines up well with the source files being about 2-3 GB and the object files 2.7GB, when checking sizes with the du command, which again suggests 120-180K source files and ~40K object files.

I think you need to clearly document what an "object" in that particular location really means, and enumerate each kind. Again, that is something that belongs in a README file.

There are several problems with using the proto files as the general documentation, two of them being that the fields in the config file and the proto-file are almost never the same, keyLocationMapOnBlockDevice  being an example of this, and that the depending definitions are frequently defined in a different file than where they are used,  which means that discovering what a configuration option is, and what it needs to specify, require chasing details across many files. The problem isn't reading the files, it is finding the necessary information in a timely fashion, which is why I want it in a single location.

This also means that it is difficult to discover if there new options of importance, which was the problem with https://github.com/buildbarn/bb-remote-execution/issues/76 . A single location reference for every configuration option, with multiple examples of values, even just specifying the data fieldnames and their types, would make that much easier, and I think it should be possible to autogenerate such documentation, provided that the .proto file contains the example information in their comments in a machine readable form.  (As an example of this, try to run `gn args out/foo --list` in a Chromium project, which will list all the GN variables a project can configure when building Chromium, including the comments preceding the variable declaration and their default and/or actual values).

As for the debugging, that was fairly old fashioned, using log files; That there was a tracing system available was not very obvious. Again, something that would be much more obvious if it was documented along with all the other configuration options in a single location, along with a documentation of, or links to, how to set up and use such a system.

**Comment by EdSchouten** [comment] 2020-12-22 06:40
> If this is indeed caused by hash collision, then my suggestion is that a different organization of the table should be considered. Items should only be kicked out when they have not been used for a long time, not because another item wants to use its parking spot (and remember that this problem occurred in the first build in the cache). Options include multiple entries in a single location, a reference to a different location storing the collisions, or **recalculate the location using a different formula, such as using an incrementing value N for each iteration, and using a hash(N|ref) for a ref to calculate a different location.**

You're basically describing what [HashingKeyLocationMap](https://github.com/buildbarn/bb-storage/blob/master/pkg/blobstore/local/hashing_key_location_map.go) already does. The maximum value for N is what you configure through [`key_location_map_maximum_get_attempts`](https://github.com/buildbarn/bb-storage/blob/4137f290ab3888da92d0c973a9a6f7736cf40df4/pkg/proto/configuration/blobstore/blobstore.proto#L338-L347).

> There are several problems with using the proto files as the general documentation, two of them being that the fields in the config file and the proto-file are almost never the same, keyLocationMapOnBlockDevice being an example of this, and that the depending definitions are frequently defined in a different file than where they are used, which means that discovering what a configuration option is, and what it needs to specify, require chasing details across many files. The problem isn't reading the files, it is finding the necessary information in a timely fashion, **which is why I want it in a single location.**

Then by all means, please create an Open Source project to automatically generate cross referenced documentation from Protobuf schemas. I would happily use such a tool if it were to exist. I don't think time is well spent developing something like this as part of the Buildbarn project.

> As for the debugging, that was fairly old fashioned, using log files; That there was a tracing system available was not very obvious. Again, something that would be much more obvious if it was documented along with all the other configuration options in a single location, along with a documentation of, or links to, how to set up and use such a system.

Another option would have been to just consult the Prometheus metrics that virtually all of the Buildbarn binaries expose.

- In all of your comments above, you've been trying to derive the number of objects based on metrics obtained from your source tree. Instead of doing that, you could take a look at the BlobAccess metrics to actually figure out how many objects are created during a single build.
- We literally provide metrics that allow you to detect that the key-location map is too small: `buildbarn_blobstore_hashing_key_location_map_get_too_many_attempts_total` and `buildbarn_blobstore_hashing_key_location_map_put_too_many_iterations_total`.

**Comment by YngveNPettersen** [comment] 2020-12-22 11:22
> You're basically describing what [HashingKeyLocationMap](https://github.com/buildbarn/bb-storage/blob/master/pkg/blobstore/local/hashing_key_location_map.go) already does. The maximum value for N is what you configure through `key_location_map_maximum_get_attempts`

OK, and I am using the default 8 and 32 for those settings (get and put).  As hash collision is the current theory, that suggest that one or both of those defaults are too small, too.

Re Prometheus, this is really the first time I have seen it mentioned. Yes, it is mentioned in the source, but if I have noticed it in passing, it has not appeared relevant for what I was working on. Additionally, the organization of those settings and functionality have been completely reworked since my current stable version (from February), and I had more than enough problems figuring out how to configure the new "local" storage.

Again, this is something I think should be directly mentioned in the README, or an associated "tools to use" file, with links to where to find more information, alongside the "how to calculate the cache size" page, so that new users  (especially users that are new to the area) can get more quickly informed about the possibilities.

As for autogeneration of documentation, a quick search turned up this as the second result: https://github.com/pseudomuto/protoc-gen-doc

**Comment by EdSchouten** [comment] 2020-12-22 11:27
> > You're basically describing what [HashingKeyLocationMap](https://github.com/buildbarn/bb-storage/blob/master/pkg/blobstore/local/hashing_key_location_map.go) already does. The maximum value for N is what you configure through `key_location_map_maximum_get_attempts`
> 
> OK, and I am using the default 8 and 32 for those settings (get and put). As hash collision is the current theory, that suggest that one or both of those defaults are too small, too.

That depends on the performance characteristics that you desire. It's a space-time tradeoff. If you make the hash table smaller, you need to crank those values up. If you make the hash table larger, it's safer to set these to lower values.

> Re Prometheus, this is really the first time I have seen it mentioned. Yes, it is mentioned in the source, but if I have noticed it in passing, it has not appeared relevant for what I was working on. Additionally, the organization of those settings and functionality have been completely reworked since my current stable version (from February), and I had more than enough problems figuring out how to configure the new "local" storage.
> 
> Again, this is something I think should be directly mentioned in the README, or an associated "tools to use" file, with links to where to find more information, alongside the "how to calculate the cache size" page, so that new users (especially users that are new to the area) can get more quickly informed about the possibilities.

Feel free to send a PR.

> As for autogeneration of documentation, a quick search turned up this as the second result: https://github.com/pseudomuto/protoc-gen-doc

Awesome! Feel free to send a PR to integrate it into our build.

**Comment by YngveNPettersen** [comment] 2020-12-22 11:41
> That depends on the performance characteristics that you desire. It's a space-time tradeoff. If you make the hash table smaller, you need to crank those values up. If you make the hash table larger, it's safer to set these to lower values.

As mentioned, based on my information, even the updated info, the 2M hash table should have been large enough for a single build. It wasn't enough for even 80% of the build.

Pull requests from me on these topics is not likely, since I don't have the detailed knowledge needed to implement them.

**Comment by EdSchouten** [comment] 2020-12-22 11:43
Then we'd better close this issue. There's no point in keeping this open if there is no reasonable expectation that any work is performed in this area.

**Closed by EdSchouten** 2020-12-22 11:43 UTC
